import { jsPDF } from 'jspdf'
import type { Lens, Project, Projector, Solution } from '../types'
import { feetInches, int, megapixels, pct, ppi } from './units'

/**
 * PDF system report.
 *
 * A4 portrait, millimetres. Everything is drawn as vectors (no rasterised
 * canvas) so the diagrams stay crisp when the report is printed or zoomed.
 */

const PAGE_W = 210
const PAGE_H = 297
const M = 16 // page margin
const CONTENT_W = PAGE_W - M * 2

const INK = { r: 26, g: 32, b: 44 }
const MUTED = { r: 110, g: 120, b: 135 }
const RULE = { r: 205, g: 212, b: 222 }
const ACCENT = { r: 22, g: 122, b: 185 }
const BLEND = { r: 240, g: 160, b: 40 }
const DANGER = { r: 190, g: 45, b: 45 }

type Ctx = {
  doc: jsPDF
  y: number
  page: number
}

function setFill(doc: jsPDF, c: { r: number; g: number; b: number }) {
  doc.setFillColor(c.r, c.g, c.b)
}
function setDraw(doc: jsPDF, c: { r: number; g: number; b: number }) {
  doc.setDrawColor(c.r, c.g, c.b)
}
function setText(doc: jsPDF, c: { r: number; g: number; b: number }) {
  doc.setTextColor(c.r, c.g, c.b)
}

function ensure(ctx: Ctx, needed: number) {
  if (ctx.y + needed > PAGE_H - 22) newPage(ctx)
}

function newPage(ctx: Ctx) {
  footer(ctx)
  ctx.doc.addPage()
  ctx.page += 1
  ctx.y = M
}

function footer(ctx: Ctx) {
  const { doc } = ctx
  doc.setFontSize(7)
  setText(doc, MUTED)
  setDraw(doc, RULE)
  doc.setLineWidth(0.2)
  doc.line(M, PAGE_H - 16, PAGE_W - M, PAGE_H - 16)
  doc.text(
    'Generated by Blend Calc. Figures are geometric estimates for planning only — ' +
      'verify against manufacturer datasheets and a site survey before committing.',
    M,
    PAGE_H - 12,
    { maxWidth: CONTENT_W - 20 },
  )
  doc.text(`Page ${ctx.page}`, PAGE_W - M, PAGE_H - 12, { align: 'right' })
}

/**
 * `keepWith` is the space the first chunk of the section needs. Without it a
 * heading lands at the foot of a page and its table starts on the next one,
 * which reads as a missing section.
 */
function heading(ctx: Ctx, text: string, keepWith = 22) {
  ensure(ctx, 16 + keepWith)
  const { doc } = ctx
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(11)
  setText(doc, INK)
  doc.text(text, M, ctx.y)
  ctx.y += 2
  setDraw(doc, ACCENT)
  doc.setLineWidth(0.5)
  doc.line(M, ctx.y, M + 22, ctx.y)
  ctx.y += 5
  doc.setFont('helvetica', 'normal')
}

/** A two-column label/value block. */
function kvGrid(ctx: Ctx, rows: [string, string][], cols = 2) {
  const { doc } = ctx
  const colW = CONTENT_W / cols
  const rowH = 5.6
  const perCol = Math.ceil(rows.length / cols)
  ensure(ctx, perCol * rowH + 4)
  doc.setFontSize(8.5)

  rows.forEach((row, i) => {
    const col = Math.floor(i / perCol)
    const line = i % perCol
    const x = M + col * colW
    const y = ctx.y + line * rowH
    setText(doc, MUTED)
    doc.setFont('helvetica', 'normal')
    doc.text(row[0], x, y)
    setText(doc, INK)
    doc.setFont('helvetica', 'bold')
    doc.text(row[1], x + colW - 4, y, { align: 'right' })
  })
  doc.setFont('helvetica', 'normal')
  ctx.y += perCol * rowH + 4
}

function table(ctx: Ctx, headers: string[], rows: string[][], widths: number[]) {
  const { doc } = ctx
  const rowH = 5.4
  ensure(ctx, rowH * (rows.length + 1) + 4)
  const total = widths.reduce((a, b) => a + b, 0)
  const scale = CONTENT_W / total
  const w = widths.map((x) => x * scale)

  setFill(doc, { r: 238, g: 242, b: 247 })
  doc.rect(M, ctx.y - 3.8, CONTENT_W, rowH, 'F')
  doc.setFontSize(8)
  doc.setFont('helvetica', 'bold')
  setText(doc, INK)
  let x = M + 1.5
  headers.forEach((h, i) => {
    const right = i > 0
    doc.text(h, right ? x + w[i] - 3 : x, ctx.y, { align: right ? 'right' : 'left' })
    x += w[i]
  })
  ctx.y += rowH

  doc.setFont('helvetica', 'normal')
  rows.forEach((r, ri) => {
    if (ctx.y + rowH > PAGE_H - 22) {
      newPage(ctx)
      ctx.y += 2
    }
    if (ri % 2 === 1) {
      setFill(doc, { r: 248, g: 250, b: 252 })
      doc.rect(M, ctx.y - 3.8, CONTENT_W, rowH, 'F')
    }
    setText(doc, INK)
    let cx = M + 1.5
    r.forEach((cell, i) => {
      const right = i > 0
      doc.text(cell, right ? cx + w[i] - 3 : cx, ctx.y, { align: right ? 'right' : 'left' })
      cx += w[i]
    })
    ctx.y += rowH
  })
  ctx.y += 3
}

function paragraph(ctx: Ctx, text: string, color = MUTED, size = 8) {
  const { doc } = ctx
  doc.setFontSize(size)
  setText(doc, color)
  const lines = doc.splitTextToSize(text, CONTENT_W) as string[]
  ensure(ctx, lines.length * 4 + 2)
  doc.text(lines, M, ctx.y)
  ctx.y += lines.length * 4 + 2
}

// ---------------------------------------------------------------------------
// Diagrams
// ---------------------------------------------------------------------------

/**
 * Front elevation: the screen rectangle with every projector tile drawn over
 * it and the overlap bands shaded. This is the drawing people actually look at.
 */
function frontElevation(
  ctx: Ctx,
  sol: Solution,
  columns: number,
  rows: number,
  screenW: number,
  screenH: number,
) {
  const { doc } = ctx
  const maxW = CONTENT_W
  const maxH = 74
  const aspect = sol.coveredWidth / sol.coveredHeight
  let w = maxW
  let h = w / aspect
  if (h > maxH) {
    h = maxH
    w = h * aspect
  }
  ensure(ctx, h + 16)
  const x0 = M + (CONTENT_W - w) / 2
  const y0 = ctx.y
  const sx = w / sol.coveredWidth
  const sy = h / sol.coveredHeight

  // The screen itself.
  setFill(doc, { r: 250, g: 251, b: 253 })
  setDraw(doc, INK)
  doc.setLineWidth(0.5)
  const scrW = screenW * sx
  const scrH = screenH * sy
  const scrX = x0 + (sol.coveredWidth - screenW) / 2 * sx
  const scrY = y0 + (sol.coveredHeight - screenH) / 2 * sy
  doc.rect(scrX, scrY, scrW, scrH, 'FD')

  const pitchX = sol.tileWidth * (1 - sol.hOverlap)
  const pitchY = sol.tileHeight * (1 - sol.vOverlap)

  // Shade the overlap bands first so tile outlines sit on top.
  setFill(doc, BLEND)
  for (let c = 0; c < columns - 1; c++) {
    const bx = x0 + (c * pitchX + sol.tileWidth - sol.hOverlapMetres) * sx
    doc.rect(bx, y0, sol.hOverlapMetres * sx, h, 'F')
  }
  for (let r = 0; r < rows - 1; r++) {
    const by = y0 + (r * pitchY + sol.tileHeight - sol.vOverlapMetres) * sy
    doc.rect(x0, by, w, sol.vOverlapMetres * sy, 'F')
  }

  // Tile outlines.
  setDraw(doc, ACCENT)
  doc.setLineWidth(0.35)
  doc.setFontSize(6.5)
  for (let r = 0; r < rows; r++) {
    for (let c = 0; c < columns; c++) {
      const tx = x0 + c * pitchX * sx
      const ty = y0 + r * pitchY * sy
      doc.rect(tx, ty, sol.tileWidth * sx, sol.tileHeight * sy, 'S')
      setText(doc, ACCENT)
      const label = rows > 1 ? `R${r + 1}C${c + 1}` : `P${c + 1}`
      doc.text(label, tx + 1.5, ty + 4)
    }
  }

  ctx.y = y0 + h + 5
  doc.setFontSize(7)
  setText(doc, MUTED)
  doc.text(
    `Front elevation, to scale. Blue outlines are individual projector images; ` +
      `orange is the overlap ("data double") region.`,
    M,
    ctx.y,
    { maxWidth: CONTENT_W },
  )
  ctx.y += 7
}

/** Plan view for a cylindrical screen: the arc, the tiles, and the rig. */
function planView(ctx: Ctx, sol: Solution, radius: number, arcLen: number, throwD: number) {
  const { doc } = ctx
  const size = 66
  ensure(ctx, size + 14)
  const cx = M + CONTENT_W / 2
  const y0 = ctx.y

  const theta = arcLen / radius
  // Scale so the whole arc plus the rig fits the box.
  const halfSpanX = radius * Math.sin(Math.min(theta, Math.PI) / 2)
  const depth = radius - radius * Math.cos(Math.min(theta, Math.PI) / 2)
  const scale = Math.min((CONTENT_W * 0.42) / Math.max(halfSpanX, 0.001), size / Math.max(depth + throwD * 1.15, 0.001))

  // Screen centre of curvature sits below the arc apex on the page.
  const apexY = y0 + 6
  const centreY = apexY + radius * scale

  const pt = (angle: number, r: number) => ({
    x: cx + r * Math.sin(angle) * scale,
    y: centreY - r * Math.cos(angle) * scale,
  })

  // The arc, drawn as a polyline.
  setDraw(doc, INK)
  doc.setLineWidth(0.7)
  const steps = 120
  let prev = pt(-theta / 2, radius)
  for (let i = 1; i <= steps; i++) {
    const a = -theta / 2 + (theta * i) / steps
    const p = pt(a, radius)
    doc.line(prev.x, prev.y, p.x, p.y)
    prev = p
  }

  // Tile boundaries and their sight lines.
  const thetaTile = sol.tileWidth / radius
  const pitch = (sol.tileWidth * (1 - sol.hOverlap)) / radius
  setDraw(doc, ACCENT)
  doc.setLineWidth(0.3)
  const nCols = sol.columns.length
  for (let c = 0; c < nCols; c++) {
    const phi = (c - (nCols - 1) / 2) * pitch
    const proj = pt(phi, radius - throwD)
    const l = pt(phi - thetaTile / 2, radius)
    const r = pt(phi + thetaTile / 2, radius)
    doc.line(proj.x, proj.y, l.x, l.y)
    doc.line(proj.x, proj.y, r.x, r.y)
    setFill(doc, ACCENT)
    doc.circle(proj.x, proj.y, 0.9, 'F')
  }

  ctx.y = Math.max(centreY - (radius - throwD) * scale, apexY) + 12
  if (ctx.y < y0 + 20) ctx.y = y0 + 20
  doc.setFontSize(7)
  setText(doc, MUTED)
  doc.text(
    `Plan view of the ${((arcLen / radius) * 180 / Math.PI).toFixed(1)}° arc. ` +
      `Dots are projector positions; lines are the edges of each tile.`,
    M,
    ctx.y,
    { maxWidth: CONTENT_W },
  )
  ctx.y += 7
}

// ---------------------------------------------------------------------------
// Report
// ---------------------------------------------------------------------------

export function buildReport(
  project: Project,
  sol: Solution,
  projector: Projector,
  lens: Lens | null,
): jsPDF {
  const doc = new jsPDF({ unit: 'mm', format: 'a4', orientation: 'portrait' })
  const ctx: Ctx = { doc, y: M, page: 1 }
  const geo = project.screen.geometry
  const { columns, rows } = project.array
  const count = columns * rows

  // -- Title block ----------------------------------------------------------
  setFill(doc, { r: 13, g: 27, b: 42 })
  doc.rect(0, 0, PAGE_W, 26, 'F')
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(16)
  setText(doc, { r: 255, g: 255, b: 255 })
  doc.text(project.name || 'Untitled blend', M, 13)
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(8.5)
  setText(doc, { r: 170, g: 190, b: 210 })
  const sub = [
    project.client ? `Client: ${project.client}` : null,
    `${count} × ${projector.brand} ${projector.model}`,
    new Date().toISOString().slice(0, 10),
  ]
    .filter(Boolean)
    .join('   ·   ')
  doc.text(sub, M, 20)
  ctx.y = 34

  // -- Headline figures -----------------------------------------------------
  heading(ctx, 'System summary')
  kvGrid(ctx, [
    ['Screen', geo.kind === 'flat' ? 'Flat' : `Cylindrical, r = ${geo.radius.toFixed(2)} m`],
    ['Screen size', `${geo.width.toFixed(3)} × ${geo.height.toFixed(3)} m`],
    ['Screen size (imperial)', `${feetInches(geo.width)} × ${feetInches(geo.height)}`],
    ['Screen area', `${(geo.width * geo.height).toFixed(2)} m²`],
    ['Array', `${columns} across × ${rows} high (${count} projectors)`],
    ['Placement', project.array.placement === 'per-tile' ? 'One projector per tile' : 'Common rig position'],
    ['Throw distance', `${project.array.throwDistance.toFixed(3)} m (${feetInches(project.array.throwDistance)})`],
    ['Screen gain', project.screen.gain.toFixed(2)],
  ])

  heading(ctx, 'System resolution')
  kvGrid(ctx, [
    [
      'Canvas resolution',
      `${int(sol.pixels.canvasPixelWidth)} × ${int(sol.pixels.canvasPixelHeight)} px`,
    ],
    ['Canvas pixels (unique)', megapixels(sol.pixels.uniquePixels)],
    ['Canvas aspect', `${(sol.pixels.canvasPixelWidth / sol.pixels.canvasPixelHeight).toFixed(3)}:1`],
    ['Projector native', `${int(projector.nativeWidth)} × ${int(projector.nativeHeight)} px`],
    ['Total projector pixels', megapixels(sol.pixels.totalProjectorPixels)],
    ['Pixel density', `${sol.pixelDensity.toFixed(1)} px/m  ·  ${ppi(sol.pixelDensity).toFixed(1)} PPI`],
    ['Est. screen luminance', `${sol.luminanceFootLamberts.toFixed(1)} fL  ·  ${sol.luminanceNits.toFixed(0)} nits`],
    ['Total light output', `${int(projector.lumens * count)} lm`],
  ])

  // -- The data double ------------------------------------------------------
  heading(ctx, 'Overlap — the doubled region', 46)
  paragraph(
    ctx,
    'Every pixel in a blend band is produced by two projectors (four where a ' +
      'horizontal and a vertical blend cross). Those pixels are paid for twice in ' +
      'projector count, rigging and data, but appear once on screen.',
  )
  table(
    ctx,
    ['Coverage', 'Area (canvas px)', 'Share of canvas', 'On screen'],
    [
      [
        'Single projector',
        int(sol.pixels.singleCoveredPixels),
        pct(sol.pixels.singleCoveredPixels / sol.pixels.uniquePixels),
        '—',
      ],
      [
        'Two projectors (doubled)',
        int(sol.pixels.doubleCoveredPixels),
        pct(sol.pixels.doubleCoveredPixels / sol.pixels.uniquePixels),
        `${sol.hOverlapMetres.toFixed(3)} m bands`,
      ],
      [
        'Four projectors (corners)',
        int(sol.pixels.quadCoveredPixels),
        pct(sol.pixels.quadCoveredPixels / sol.pixels.uniquePixels),
        rows > 1 ? `${sol.vOverlapMetres.toFixed(3)} m tall` : '—',
      ],
    ],
    [34, 22, 20, 24],
  )
  kvGrid(
    ctx,
    [
      ['Horizontal blend', `${pct(sol.hOverlap)} of image  ·  ${int(sol.pixels.hBlendPixels)} px  ·  ${sol.hOverlapMetres.toFixed(3)} m`],
      ['Vertical blend', rows > 1 ? `${pct(sol.vOverlap)} of image  ·  ${int(sol.pixels.vBlendPixels)} px  ·  ${sol.vOverlapMetres.toFixed(3)} m` : 'n/a (single row)'],
      ['Redundant pixels', `${megapixels(sol.pixels.redundantPixels)} (${int(sol.pixels.redundantPixels)})`],
      ['Pixel efficiency loss', pct(sol.pixels.overlapEfficiencyLoss)],
    ],
    1,
  )

  // -- Diagram --------------------------------------------------------------
  heading(ctx, 'Layout', 60)
  frontElevation(ctx, sol, columns, rows, geo.width, geo.height)
  if (geo.kind === 'cylindrical') {
    planView(ctx, sol, geo.radius, geo.width, project.array.throwDistance)
  }

  // -- Optics ---------------------------------------------------------------
  heading(ctx, 'Optics and lens', 34)
  kvGrid(ctx, [
    ['Image per projector', `${sol.tileWidth.toFixed(3)} × ${sol.tileHeight.toFixed(3)} m`],
    ['Image (imperial)', `${feetInches(sol.tileWidth)} × ${feetInches(sol.tileHeight)}`],
    ['Lens', lens ? lens.name : 'Not selected'],
    ['Lens range', lens ? `${lens.throwRatioMin.toFixed(2)}–${lens.throwRatioMax.toFixed(2)}:1` : '—'],
    [
      'Required throw ratio',
      `${Math.min(...sol.columns.map((c) => c.requiredThrowRatio)).toFixed(3)}–${Math.max(
        ...sol.columns.map((c) => c.requiredThrowRatio),
      ).toFixed(3)}:1`,
    ],
    [
      'Zoom position',
      lens && lens.throwRatioMax > lens.throwRatioMin
        ? `${pct(sol.lensZoomPosition, 0)} from wide`
        : 'Fixed lens',
    ],
  ])

  if (geo.kind === 'cylindrical' || project.array.placement === 'common-point') {
    table(
      ctx,
      ['Column', 'Throw', 'Slant', 'Image width', 'Throw ratio', 'H shift', 'Off-axis'],
      sol.columns.map((c) => [
        `${c.column + 1}`,
        `${c.throwDistance.toFixed(3)} m`,
        `${c.slantDistance.toFixed(3)} m`,
        `${c.flatImageWidth.toFixed(3)} m`,
        `${c.requiredThrowRatio.toFixed(3)}:1`,
        `${c.hShiftPct.toFixed(1)}%`,
        `${c.offAxisDeg.toFixed(1)}°`,
      ]),
      [14, 18, 18, 20, 18, 14, 14],
    )
    paragraph(
      ctx,
      'Throw is the perpendicular distance the throw ratio is defined against. Slant is the ' +
        'straight-line distance to the tile centre — the one you measure on site.',
    )
    if (geo.kind === 'cylindrical') {
      kvGrid(
        ctx,
        [
          ['Wrap angle', `${sol.wrapAngleDeg.toFixed(1)}°`],
          ['Chord width', `${(2 * geo.radius * Math.sin(geo.width / geo.radius / 2)).toFixed(3)} m`],
          ['Height at tile edge', `${pct(sol.curveHeightRatio)} of centre — oversize and mask the difference`],
        ],
        1,
      )
    }
  }

  // -- Per-projector schedule ----------------------------------------------
  heading(ctx, 'Projector schedule', 34)
  const schedule: string[][] = []
  for (let r = 0; r < rows; r++) {
    for (let c = 0; c < columns; c++) {
      const optics = sol.columns[c]
      schedule.push([
        rows > 1 ? `R${r + 1}C${c + 1}` : `P${c + 1}`,
        `${projector.brand} ${projector.model}`,
        lens ? lens.name : '—',
        `${optics.requiredThrowRatio.toFixed(3)}:1`,
        `${optics.slantDistance.toFixed(2)} m`,
        `${c > 0 ? 'L' : '·'}${c < columns - 1 ? 'R' : '·'}${r > 0 ? 'T' : '·'}${r < rows - 1 ? 'B' : '·'}`,
      ])
    }
  }
  table(
    ctx,
    ['Position', 'Body', 'Lens', 'Throw ratio', 'Throw', 'Blend edges'],
    schedule,
    [16, 34, 30, 18, 16, 18],
  )
  paragraph(
    ctx,
    'Blend edges: L/R/T/B marks which edges of that projector carry a soft edge. ' +
      'A dot means that edge is a hard edge of the canvas.',
  )

  // -- Diagnostics ----------------------------------------------------------
  if (sol.diagnostics.length) {
    heading(ctx, 'Notes and warnings', 14)
    doc.setFontSize(8)
    for (const d of sol.diagnostics) {
      const color = d.severity === 'error' ? DANGER : d.severity === 'warning' ? { r: 170, g: 110, b: 20 } : MUTED
      const label = d.severity === 'error' ? 'ERROR' : d.severity === 'warning' ? 'WARNING' : 'NOTE'
      const lines = doc.splitTextToSize(`${label}: ${d.message}`, CONTENT_W - 4) as string[]
      ensure(ctx, lines.length * 3.8 + 3)
      setDraw(doc, color)
      doc.setLineWidth(0.9)
      doc.line(M, ctx.y - 3, M, ctx.y + lines.length * 3.8 - 4)
      setText(doc, color)
      doc.text(lines, M + 3, ctx.y)
      ctx.y += lines.length * 3.8 + 2.5
    }
  }

  if (projector.unverified) {
    ensure(ctx, 16)
    setFill(doc, { r: 253, g: 240, b: 235 })
    setDraw(doc, DANGER)
    doc.setLineWidth(0.4)
    doc.rect(M, ctx.y - 4, CONTENT_W, 13, 'FD')
    setText(doc, DANGER)
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(8)
    doc.text('Unverified projector data', M + 3, ctx.y + 0.5)
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(7.5)
    doc.text(
      `The specifications for ${projector.brand} ${projector.model} are seed data shipped with ` +
        `the app and have not been checked against a datasheet. Confirm before ordering.`,
      M + 3,
      ctx.y + 5,
      { maxWidth: CONTENT_W - 6 },
    )
    ctx.y += 16
  }

  if (project.notes?.trim()) {
    heading(ctx, 'Project notes', 14)
    paragraph(ctx, project.notes.trim(), INK, 8.5)
  }

  footer(ctx)
  return doc
}

export function reportFilename(project: Project): string {
  const safe = (project.name || 'blend').replace(/[^a-z0-9]+/gi, '-').replace(/^-|-$/g, '')
  return `${safe.toLowerCase() || 'blend'}-report.pdf`
}
